spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spoty-live
    username: progmatic
    password: progmatic
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      port: 35730
    restart:
      exclude: templates/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 300KB
      max-request-size: 10MB
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
output:
    ansi:
      enabled: ALWAYS
server:
  port: 8082
logging:
  level:
    web: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%15X{user}){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}'
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: tesztuser
    password: tesztpass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: eles
  datasource:
    url: jdbc:mysql://adatbazis_eles:3306/spoty-live
    username: progmatic
    password: progmatic
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 80
  tomcat:
    threads:
      max: 5