version: "3.7"

services:
  adatbazis_eles:
    container_name: spoty-live-adatbazis
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spoty-live
      MYSQL_USER: progmatic
      MYSQL_PASSWORD: progmatic
    ports:
      - "3306:3306"
  email_dev:
    image: maildev/maildev
    container_name: email_dev
    ports:
      - "1025:25"
      - "1080:80"
    restart: always
  app_eles:
    container_name: spoti-live-eles
    build: ..
    environment:
      - PROFILES=eles
      - TZ=Europe/Budapest
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - adatbazis_eles
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--insecure", "http://localhost:8080/" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 120s
    restart: always
